#!/usr/bin/env python3
from __future__ import annotations

import re
import shutil
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CLAUDE = ROOT / ".claude"
AGENTS = ROOT / ".agents"
CODEX = ROOT / ".codex"
OMX_AGENT_NAMES = {
  "analyst",
  "architect",
  "code-reviewer",
  "code-simplifier",
  "critic",
  "debugger",
  "dependency-expert",
  "designer",
  "executor",
  "explore",
  "git-master",
  "planner",
  "researcher",
  "team-executor",
  "test-engineer",
  "verifier",
  "vision",
  "writer",
}


def parse_frontmatter(text: str):
  match = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)$", text, re.S)
  if not match:
    return {}, text.strip()

  raw, body = match.groups()
  data = {}
  for line in raw.splitlines():
    if ":" not in line:
      continue
    key, value = line.split(":", 1)
    data[key.strip()] = value.strip().strip("\"'")
  return data, body.strip()


def toml_escape(value: str) -> str:
  return value.replace("\\", "\\\\").replace('"', '\\"')


def copy_tree_contents(src: Path, dst: Path):
  if not src.exists():
    return

  dst.mkdir(parents=True, exist_ok=True)
  for item in src.iterdir():
    target = dst / item.name
    if item.is_dir():
      if target.exists():
        shutil.rmtree(target)
      shutil.copytree(item, target, ignore=shutil.ignore_patterns(".git"))
    else:
      shutil.copy2(item, target)


def convert_agent(src: Path, dst: Path):
  text = src.read_text(encoding="utf-8")
  fm, body = parse_frontmatter(text)
  name = fm.get("name", src.stem)
  description = fm.get("description", f"Migrated Claude agent: {name}")
  codex_name = dst.stem
  instructions = (
    f"# Source: .claude/agents/{src.name}\n"
    f"# Original Claude agent name: {name}\n\n"
    f"{body}"
  )
  dst.write_text(
    "# local-claude-agent: generated by .codex/sync-claude-to-codex.py\n"
    f'name = "{toml_escape(codex_name)}"\n'
    f'description = "{toml_escape(description)}"\n'
    f"developer_instructions = {json.dumps(instructions, ensure_ascii=False)}\n",
    encoding="utf-8",
  )


def convert_command(src: Path, skills_dir: Path):
  text = src.read_text(encoding="utf-8")
  fm, body = parse_frontmatter(text)
  base = src.stem
  skill_name = f"source-command-{base}"
  description = fm.get("description", f"Migrated Claude slash command: /{base}")
  body = body.replace("~/.claude/", ".codex/").replace(".claude/", ".codex/")
  skill_dir = skills_dir / skill_name
  skill_dir.mkdir(parents=True, exist_ok=True)
  (skill_dir / "SKILL.md").write_text(
    "---\n"
    f'name: "{skill_name}"\n'
    f'description: "{description.replace(chr(34), chr(92) + chr(34))}"\n'
    "---\n\n"
    f"# {skill_name}\n\n"
    f"Use this skill when the user asks to run the migrated source command `/{base}`.\n\n"
    "## Command Template\n\n"
    f"{body}\n",
    encoding="utf-8",
  )


def sync():
  if not CLAUDE.exists():
    raise SystemExit(f"Missing {CLAUDE}")

  skills_dir = AGENTS / "skills"
  codex_agents_dir = CODEX / "agents"
  skills_dir.mkdir(parents=True, exist_ok=True)
  codex_agents_dir.mkdir(parents=True, exist_ok=True)

  for name in ["skills", "rules", "contexts", "docs", "hooks", "mcp-configs"]:
    copy_tree_contents(CLAUDE / name, AGENTS / name)

  for src in sorted((CLAUDE / "commands").glob("*.md")):
    convert_command(src, skills_dir)

  for src in sorted((CLAUDE / "agents").glob("*.md")):
    target_name = f"local-{src.stem}" if src.stem in OMX_AGENT_NAMES else src.stem
    convert_agent(src, codex_agents_dir / f"{target_name}.toml")

  claude_md = CLAUDE / "CLAUDE.md"
  if claude_md.exists():
    agents_md = ROOT / "AGENTS.md"
    if agents_md.exists() and "OMX:AGENTS:START" in agents_md.read_text(encoding="utf-8"):
      print("AGENTS.md has OMX markers; preserving merged project instructions")
      return

    guide = claude_md.read_text(encoding="utf-8")
    guide = guide.replace("Claude Code", "Codex")
    guide = guide.replace("메인 Claude", "메인 Codex")
    guide = guide.replace("Claude)", "Codex)")
    guide = guide.replace("~/.claude/", ".codex/")
    if "## Codex 자동 로딩 위치" not in guide:
      guide = guide.rstrip() + (
        "\n\n## Codex 자동 로딩 위치\n"
        "- 원본 설정: `.claude/`\n"
        "- Codex 프로젝트 지침: `AGENTS.md`\n"
        "- Codex 스킬/슬래시 커맨드 변환본: `.agents/skills/`\n"
        "- Codex 에이전트 변환본: `.codex/agents/`\n"
        "- WSL CLI에서는 `codex-myapp` 또는 `codex -C /home/pabang/myapp`로 실행한다.\n"
      )
    agents_md.write_text(guide, encoding="utf-8")

  print(
    f"synced agents={len(list(codex_agents_dir.glob('*.toml')))} "
    f"skills={len([p for p in skills_dir.iterdir() if p.is_dir()])}"
  )


if __name__ == "__main__":
  sync()
